# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-04-06 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='joined_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
